#!/usr/bin/env python3
"""Convert source images in assets/ to LVGL true-color C arrays.

Output goes to firmware/src/assets/generated/<name>.c and contains:
  - the raw RGB565 byte data (high-byte first, matching LV_COLOR_16_SWAP=1)
  - an lv_img_dsc_t named <name>_dsc that the renderer references

Add new images by appending to the SOURCES list below. The renderer registers
them via firmware/src/builtin_images.cpp.
"""
from __future__ import annotations

import pathlib
from PIL import Image, ImageEnhance, ImageFile

ImageFile.LOAD_TRUNCATED_IMAGES = True
ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "firmware" / "src" / "assets" / "generated"

SOURCES = [
    {
        "name": "claude_logo",
        "src":  ROOT / "assets" / "claude_logo.webp",
        "max_w": 320,
        "max_h": 208,
        "saturation": 1.6,
        "contrast": 1.1,
        "brightness": 0.85,
    },
    {
        "name": "ollama_logo",
        "src":  ROOT / "assets" / "ollama_logo.png",
        "max_w": 280,
        "max_h": 185,
        # Pixel-art logo: remap bright pixels → sunflower yellow, dark → bg.
        "colorize_fg": (245, 197, 24),   # #F5C518
        "colorize_bg": (17,  17,  17),   # #111111
        "colorize_threshold": 100,
    },
]


def convert(spec: dict) -> None:
    img = Image.open(spec["src"]).convert("RGB")
    img.thumbnail((spec["max_w"], spec["max_h"]), Image.LANCZOS)
    if spec.get("saturation"):
        img = ImageEnhance.Color(img).enhance(spec["saturation"])
    if spec.get("contrast"):
        img = ImageEnhance.Contrast(img).enhance(spec["contrast"])
    if spec.get("brightness"):
        img = ImageEnhance.Brightness(img).enhance(spec["brightness"])
    if spec.get("colorize_fg"):
        fg  = spec["colorize_fg"]
        bg  = spec.get("colorize_bg", (0, 0, 0))
        thr = spec.get("colorize_threshold", 128)
        px  = img.load()
        w0, h0 = img.size
        for y in range(h0):
            for x in range(w0):
                r, g, b = px[x, y]
                px[x, y] = fg if (r + g + b) / 3 > thr else bg
    w, h = img.size

    data = bytearray()
    px = img.load()
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            # LV_COLOR_16_SWAP=1 → high byte first in memory.
            data.append((rgb565 >> 8) & 0xFF)
            data.append(rgb565 & 0xFF)

    name = spec["name"]
    out = OUT_DIR / f"{name}.c"
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    lines = [
        "// Auto-generated by scripts/convert_image.py — do not edit.",
        "#include <lvgl.h>",
        "",
        f"static const uint8_t __attribute__((aligned(4))) {name}_data[] = {{",
    ]
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i : i + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append("")
    lines.append(f"const lv_img_dsc_t {name}_dsc = {{")
    lines.append("    .header = {")
    lines.append("        .cf = LV_IMG_CF_TRUE_COLOR,")
    lines.append("        .always_zero = 0,")
    lines.append("        .reserved = 0,")
    lines.append(f"        .w = {w},")
    lines.append(f"        .h = {h},")
    lines.append("    },")
    lines.append(f"    .data_size = {len(data)},")
    lines.append(f"    .data = {name}_data,")
    lines.append("};")
    lines.append("")
    out.write_text("\n".join(lines))
    print(f"Wrote {out} ({w}x{h}, {len(data)} bytes)")


def main() -> None:
    for spec in SOURCES:
        convert(spec)


if __name__ == "__main__":
    main()
